runtime: java
env: flex

service: default

runtime_config:
  jdk: openjdk8

handlers:
  - url: /.*
    script: this field is required, but ignored

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10

health_check:
  enable_health_check: True

#env_variables:
#  ENCRYPT_KEY: your_encryption_key_here

beta_settings:
  cloud_sql_instances: ozeronews:europe-north1:ozerodb